<?php
  $lang['number']		= 'Order #';
  $lang['date'] 		= 'Date';
  $lang['time']			= 'Status';
  $lang['due'] 			= 'Due date';
  $lang['to'] 			= 'Ship to:';
  $lang['from'] 		= 'Invoice By:';
  $lang['product'] 		= 'Product';
  $lang['qty'] 			= 'Qty';
  $lang['price'] 		= 'Price';
  $lang['discount'] 	= 'Shipping';
  $lang['vat'] 			= 'Vat';
  $lang['total'] 		= 'Total';
  $lang['page'] 		= 'Page';
  $lang['page_of'] 		= 'of';
?>